name: Build, Push and Update DevOps Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/attendance:${{ github.sha }}

      - name: Checkout DevOps repo
        uses: actions/checkout@v4
        with:
          repository: srujankn762/devops
          token: ${{ secrets.DEVOPS_REPO_PAT }}
          path: devops

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: ghcr.io/${{ github.repository_owner }}/attendance:.*|image: ghcr.io/${{ github.repository_owner }}/attendance:${{ github.sha }}|" \
          devops/attendance/k8s/app/deployment.yaml

      - name: Commit and push to DevOps repo
        run: |
          cd devops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add attendance/k8s/app/deployment.yaml
          git commit -m "chore: update attendance image to ${{ github.sha }}"
          git push
